version: '3'
 
services:
    apache_img:
        container_name: avers_apache_con
        build:
            context: ./apache
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
        volumes:
            - ../logs/apache:${APACHE_ROOT_DIR}/logs
            - ../avers:/usr/local/apache2/htdocs
        ports:
            - ${APACHE_EXPOSED_PORT}:80
        networks:
            public_net:
                ipv4_address: ${APACHE_IP}
        environment:
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - APACHE_ROOT_DIR=${APACHE_ROOT_DIR}
            - PHP_IP=${PHP_IP}
            - PHP_APP_DIR=${PHP_APP_DIR}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
    mysql_img:
        container_name: avers_mysql_con
        image: mysql:5.6
        restart: unless-stopped
        tty: true
        volumes:
            - ./database:${MYSQL_DATA_DIR}
        ports: 
            - "33061:3306"
        networks:
            public_net:
                ipv4_address: ${MYSQL_IP}
        environment:
            MYSQL_DATABASE: avers
            MYSQL_USER: default
            MYSQL_PASSWORD: root
            MYSQL_ROOT_PASSWORD: root
    php_img:
        container_name: avers_php_con
        build:
            context: ./php
            args:
                - WEB_USER=${WEB_USER}
                - WEB_GROUP=${WEB_GROUP}
                - PHP_ROOT_DIR=${PHP_ROOT_DIR}
        working_dir: ${PHP_APP_DIR}
        volumes:
            - ../avers:${PHP_APP_DIR}
            - ../logs/php:${PHP_ROOT_DIR}/logs
        depends_on:
            - apache_img
            - mysql_img
        networks:
            public_net:
                ipv4_address: ${PHP_IP}
        environment:
            - PHP_ROOT_DIR=${PHP_ROOT_DIR}
            - APACHE_IP=${APACHE_IP}
            - APACHE_EXPOSED_PORT=${APACHE_EXPOSED_PORT}
            - WEB_USER=${WEB_USER}
            - WEB_GROUP=${WEB_GROUP}
            - MYSQL_IP=${MYSQL_IP}
            - MYSQL_ROOT_USER=${MYSQL_ROOT_USER}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
 
networks:
    public_net:
        driver: bridge
        ipam:
            driver: default
            config:
                - subnet: ${NETWORK_SUBNET}